name: widget-server pipe

on:
  push:
    branches: 
      - 'main'

jobs:
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ VARS.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push the image to AWS ECR
        id: build-push-image
        run: |
          docker bukld -t widget-server:v3
          docker tag widget-server:v3 776051122812.dkr.ecr.us-east-2.amazonaws.com/al3xandr3sl/widget-server
          docker push 776051122812.dkr.ecr.us-east-2.amazonaws.com/al3xandr3sl/widget-server